# Project information
site_name: YorkFish's blog
site_url: https://yorkfish.github.io/blogs/
site_author: YorkYu
site_description: notes of learning

# Copyright
copyright: 'Copyright &copy; 2020 YorkFish'

# Configuration
theme:
  name: material
  language: zh
  features:
    - tabs

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YorkFish
      name: github

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# MathJax, Chart
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.12.0/flowchart.min.js
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
  - javascripts/umlconvert.js

nav:
  - "index": index.md
  - "MkDocs":
    - "0 快速上手": MkDocs/00_quick_start.md
    - "1 安装": MkDocs/01_install.md
    - "2 新建日志项目": MkDocs/02_new_log_item.md
    - "3 编辑配置文件": MkDocs/03_edit_config_file.md
    - "4 导出": MkDocs/04_export.md
    - "5 部署": MkDocs/05_deploy_to_the_cloud.md
    - "Material-Markdown":
      - "1 提示框": MkDocs/Material/01_admonitions.md
      - "2 代码块": MkDocs/Material/02_code_blocks.md
      - "3 Caret-Mark-Tilde": MkDocs/Material/03_caret_mark_tilde.md
      - "4 表情符号与任务列表": MkDocs/Material/04_emoji_and_task_list.md
      - "5 图表": MkDocs/Material/05_flow_chart.md
      - "6 数学公式": MkDocs/Material/06_mathematical_formula.md
  - "Editors":
    - "Preview": Editors/preview.md
    - "Jupyter Notebook":
      - "01 安装并修改默认开启路径": Editors/JupyterNotebook/01_install.md
      - "02 初识": Editors/JupyterNotebook/02_first_acquaintance.md
      - "03 命令模式的快捷键": Editors/JupyterNotebook/03_shortcut_keys_for_command_mode.md
      - "04 编辑模式的快捷键": Editors/JupyterNotebook/04_shortcut_key_for_edit_mode.md
    - "Sublime Text 3":
      - "01 基础设置": Editors/SublimeText3/01_basic_settings.md
      - "02 快捷键": Editors/SublimeText3/02_shortcut_keys.md
      - "03 Python3 运行环境": Editors/SublimeText3/03_python3_operating_env.md
      - "04 C 运行环境": Editors/SublimeText3/04_c_operating_env.md
      - "05 C++ 运行环境": Editors/SublimeText3/05_cpp_operating_env.md
      - "06 Makefile": Editors/SublimeText3/06_makefile.md
      - "07 HTML 运行环境": Editors/SublimeText3/07_html_operating_env.md
      - "08 Snippet": Editors/SublimeText3/08_snippet.md
      - "09 plugin": Editors/SublimeText3/09_plugin.md
      - "插件":
        - "01 Package Control": Editors/SublimeText3/10_package_control.md
        - "02 A File Icon": Editors/SublimeText3/a_file_icon.md
        - "03 Anaconda": Editors/SublimeText3/anaconda.md
        - "04 Python PEP8 Autoformat": Editors/SublimeText3/python_pep8_autoformat.md
        - "05 SublimeGDB": Editors/SublimeText3/sublimegdb.md
        - "06 sublimeREPL": Editors/SublimeText3/sublimerepl.md
        - "07 Vintageous": Editors/SublimeText3/vintageous.md
        - "08 Virtualenv": Editors/SublimeText3/virtualenv.md
        - "09 Theme - ayu": Editors/SublimeText3/theme-ayu.md
        - "10 Theme - Spacegray": Editors/SublimeText3/theme-spacegray.md
    - "Vim":
      - "Gvim":
        - "01 “3+1”种膜模式": Editors/Gvim/01_three_and_one_modes.md
        - "02 定位命令": Editors/Gvim/02_positioning_command.md
        - "03 删除命令": Editors/Gvim/03_delete_command.md
        - "04 插入命令": Editors/Gvim/04_insert_command.md
        - "05 删除并插入": Editors/Gvim/05_delete_and_insert.md
        - "06 复制与粘贴": Editors/Gvim/06_copy_and_paste.md
        - "07 搜索与替换": Editors/Gvim/07_search_and_replace.md
        - "08 后悔药与特殊字符": Editors/Gvim/08_regret_medicine_and_special_characters.md
        - "09 保存与退出": Editors/Gvim/09_save_and_exit.md
        - "10 添加注释": Editors/Gvim/10_multiline_comments.md
        - "11 映射": Editors/Gvim/11_map.md
        - "12 合并文件与打开多个文件": Editors/Gvim/12_files.md
        - "13 简洁流配置": Editors/Gvim/13_simple_configuration.md
      - "Neovim":
        - "01 安装": Editors/Neovim/01_install.md
        - "02 基本设置": Editors/Neovim/02_basic_settings.md
        - "03 基本映射": Editors/Neovim/03_basic_mappings.md
        - "04 光标移动": Editors/Neovim/04_cursor_movement.md
        - "05 分屏": Editors/Neovim/05_window_management.md
        - "06 标签页": Editors/Neovim/06_tab_management.md
        - "07 配色设置": Editors/Neovim/07_color.md
        - "08 Markdown": Editors/Neovim/08_markdown_settings.md
        - "09 一键执行": Editors/Neovim/09_one_click_execution.md
        - "插件":
          - "01 Vim-Plug 的使用": Editors/Neovim/10_Vim-Plug.md
          - "02 vim-airline": Editors/Neovim/11_vim-airline.md
          - "03 NERDTree": Editors/Neovim/12_nerdtree.md
  - "Git":
    - "GitHub 上的使用":
      - "01 在 GitHub 上新建仓库": Git/GitHub/01_在图形界面新建仓库.md
      - "02 往仓库里添加文件": Git/GitHub/02_往仓库里添加文件.md
      - "03 修改仓库里的文件": Git/GitHub/03_修改仓库里的文件.md
      - "04 查看历史记录": Git/GitHub/04_查看历史记录.md
      - "05 创建分支与切换分支": Git/GitHub/05_创建分支与切换分支.md
      - "06 查看历史图像": Git/GitHub/06_查看历史图像.md
      - "07 合并分支": Git/GitHub/07_合并分支.md
      - "08 将远程仓库克隆到本地": Git/GitHub/08_将远程仓库克隆到本地.md
    - "GitBash 下的操作":
      - "01 设置身份信息": Git/GitBash/01_设置身份信息.md
      - "02 创建 SSH Key": Git/GitBash/02_创建密钥.md
      - "03 在 GitHub 上添加公钥": Git/GitBash/03_添加公钥.md
      - "04 克隆远程仓库": Git/GitBash/04_克隆远程仓库.md
      - "05 本地仓库关联远程仓库": Git/GitBash/05_本地仓库关联远程仓库.md
      - "06 本地仓库向远程仓库推送": Git/GitBash/06_本地仓库向远程仓库推送.md
      - "07 连接失败问题的解决": Git/GitBash/07_连接失败问题的解决.md
      - "08 删除远程仓库": Git/GitBash/08_删除远程仓库.md
      - "09 在本地建一个仓库": Git/GitBash/09_在本地建一个仓库.md
      - "10 三棵树": Git/GitBash/10_三棵树.md
      - "11 向本地仓库添加文件": Git/GitBash/11_向本地仓库添加文件.md
      - "12 status": Git/GitBash/12_status.md
      - "13 commit": Git/GitBash/13_commit.md
      - "14 log": Git/GitBash/14_log.md
      - "15 checkout file": Git/GitBash/15_checkout_file.md
      - "16 diff": Git/GitBash/16_diff.md
      - "17 reset": Git/GitBash/17_reset.md
      - "18 rm": Git/GitBash/18_rm.md
      - "19 branch & checkout branch": Git/GitBash/19_branch&checkout_branch.md
      - "20 制造冲突一": Git/GitBash/20_制造冲突一.md
      - "21 制造冲突二": Git/GitBash/21_制造冲突二.md
      - "22 制造冲突三": Git/GitBash/22_制造冲突三.md
      - "23 解决冲突": Git/GitBash/23_解决冲突.md
      - "24 merge": Git/GitBash/24_merge.md
      - "25 stash1": Git/GitBash/25_stash1.md
      - "26 stash2": Git/GitBash/26_stash2.md
      - "27 删除未合并的分支": Git/GitBash/27_删除未合并的分支.md
      - "28 推拉": Git/GitBash/28_推拉.md
      - "29 rebase": Git/GitBash/29_rebase.md
      - "30 tag": Git/GitBash/30_tag.md
      - "31 config": Git/GitBash/31_config.md
  - "Linux":
    - "基础知识":
      - "001 Unix": Linux/001_Unix.md
      - "002 Linux": Linux/002_Linux.md
      - "003 预备知识": Linux/003_预备知识.md
      - "004 分区": Linux/004_分区.md
      - "005 安装": Linux/005_安装.md
      - "006 常见目录及其作用": Linux/006_常见目录及其作用.md
      - "007 一些注意事项": Linux/007_一些注意事项.md
      - "008 命令格式": Linux/008_命令格式.md
    - "目标处理命令":
      - "009 ls": Linux/009_ls.md
      - "010 mkdir": Linux/010_mkdir.md
      - "011 cd": Linux/011_cd.md
      - "012 pwd": Linux/012_pwd.md
      - "013 rmdir": Linux/013_rmdir.md
      - "014 cp": Linux/014_cp.md
      - "015 mv": Linux/015_mv.md
      - "016 rm": Linux/016_rm.md
    - "文件处理命令":
      - "017 touch": Linux/017_touch.md
      - "018 cat": Linux/018_cat.md
      - "019 tac": Linux/019_tac.md
      - "020 more": Linux/020_more.md
      - "021 less": Linux/021_less.md
      - "022 head": Linux/022_head.md
      - "023 tail": Linux/023_tail.md
    - "链接命令":
      - "024 链接命令 ln": Linux/024_ln.md
    - "权限管理命令":
      - "025 chmod": Linux/025_chmod.md
      - "026 chown": Linux/026_chown.md
      - "027 chgrp": Linux/027_chgrp.md
      - "028 umask": Linux/028_umask.md
    - "文件搜索命令":
      - "029 find": Linux/029_find.md
      - "030 locate": Linux/030_locate.md
      - "031 which": Linux/031_which.md
      - "032 whereis": Linux/032_whereis.md
      - "033 grep": Linux/033_grep.md
    - "帮助命令":
      - "034 man": Linux/034_man.md
      - "035 help": Linux/035_help.md
    - "用户管理命令":
      - "036 useradd": Linux/036_useradd.md
      - "037 passwd": Linux/037_passwd.md
      - "038 who": Linux/038_who.md
      - "039 w": Linux/039_w.md
    - "压缩解压命令":
      - "040 gzip": Linux/040_gzip.md
      - "041 gunzip": Linux/041_gunzip.md
      - "042 tar": Linux/042_tar.md
      - "043 zip": Linux/043_zip.md
      - "044 unzip": Linux/044_unzip.md
      - "045 bzip2": Linux/045_bzip2.md
      - "046 bunzip2": Linux/046_bunzip2.md
    - "网络命令":
      - "047 write": Linux/047_write.md
      - "048 well": Linux/048_wall.md
      - "049 ping": Linux/049_ping.md
      - "050 ifconfig": Linux/050_ifconfig.md
      - "051 mail": Linux/051_mail.md
      - "052 last": Linux/052_last.md
      - "053 lastlog": Linux/053_lastlog.md
      - "054 traceroute": Linux/054_traceroute.md
      - "055 netstat": Linux/055_netstat.md
      - "056 setup": Linux/056_setup.md
    - "挂载命令":
      - "057 挂载命令 mount": Linux/057_mount.md
    - "关机重启等命令":
      - "058 关机命令": Linux/058_关机命令.md
      - "059 重启命令": Linux/059_重启命令.md
      - "060 登出命令": Linux/060_logout.md
    - "RPM 命令管理":
      - "061 软件包管理简介": Linux/061_软件包管理简介.md
      - "062 RPM 包的命名原则与依赖性": Linux/062_RPM_包名与依赖性.md
      - "063 RPM 包的安装、升级与卸载": Linux/063_RPM_包的安装、升级与卸载.md
      - "064 RPM 包的查询": Linux/064_RPM_包的查询.md
      - "065 RPM 包的校验": Linux/065_RPM_包的校验.md
      - "066 RPM 包的文件提取": Linux/066_RPM_包的文件提取.md
    - "IP & yum":
      - "067 IP 地址的配置": Linux/067_IP_地址的配置.md
      - "068 网络 yum 源": Linux/068_网络_yum_源.md
      - "069 yum 命令": Linux/069_yum_命令.md
      - "070 光盘 yum 源搭建": Linux/070_光盘_yum_源搭建.md
    - "源码包安装":
      - "071 RPM 包与源码包的区别": Linux/071_RPM_包与源码包的区别.md
      - "072 源码包的安装过程": Linux/072_源码包的安装过程.md
    - "脚本安装":
      - "073 脚本安装": Linux/073_脚本安装包.md
  - "Markdown":
    - "01 目录与标题": Markdown/01_toc_and_title.md
    - "02 引用与标记": Markdown/02_quote_and_sign.md
    - "03 代码块": Markdown/03_code_blocks.md
    - "04 表格": Markdown/04_table.md
    - "05 转义字符": Markdown/05_escape_character.md
    - "06 列表": Markdown/06_lists.md
    - "07 分割线": Markdown/07_split_line.md
    - "08 下划线": Markdown/08_underline.md
    - "09 删除线": Markdown/09_strikethrough.md
    - "10 “三体”": Markdown/10_emphasis.md
    - "11 注脚与上下标": Markdown/11_footnotes_and_sup-sub.md
    - "12 插入链接": Markdown/12_links.md
    - "13 插入图片": Markdown/13_images.md
    - "14 YAML 题头": Markdown/14_YAML.md
    - "15 缩写": Markdown/15_abbreviation.md
    - "16 按键与任务列表": Markdown/16_kbd_and_task_list.md
    - "17 emoji": Markdown/17_emoji.md
    - "18 LaTex": Markdown/18_LaTeX.md
    - "19 Flow Chart": Markdown/19_flow.md
    - "20 GANTT": Markdown/20_GANTT.md
    - "21 UML": Markdown/21_UML.md
  - "about": about.md
