site_name: YorkFish

theme:
    name: "material"

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
    - "index": index.md

    - "DS+Algo":
        - "to be continued": DS+Algo/to be continued.md

    - "Git":
        - "GitHub 上的使用":
            - "01 在 GitHub 上新建仓库": Git/GitHub/01_在图形界面新建仓库.md
            - "02 往仓库里添加文件": Git/GitHub/02_往仓库里添加文件.md
            - "03 修改仓库里的文件": Git/GitHub/03_修改仓库里的文件.md
            - "04 查看历史记录": Git/GitHub/04_查看历史记录.md
            - "05 创建分支与切换分支": Git/GitHub/05_创建分支与切换分支.md
            - "06 查看历史图像": Git/GitHub/06_查看历史图像.md
            - "07 合并分支": Git/GitHub/07_合并分支.md
            - "08 将远程仓库克隆到本地": Git/GitHub/08_将远程仓库克隆到本地.md
        - "GitBash 下的操作":
            - "01 设置身份信息": Git/GitBash/01_设置身份信息.md
            - "02 创建 SSH Key": Git/GitBash/02_创建密钥.md
            - "03 在 GitHub 上添加公钥": Git/GitBash/03_添加公钥.md
            - "04 克隆远程仓库": Git/GitBash/04_克隆远程仓库.md
            - "05 本地仓库关联远程仓库": Git/GitBash/05_本地仓库关联远程仓库.md
            - "06 本地仓库向远程仓库推送": Git/GitBash/06_本地仓库向远程仓库推送.md
            - "07 连接失败问题的解决": Git/GitBash/07_连接失败问题的解决.md
            - "08 删除远程仓库": Git/GitBash/08_删除远程仓库.md
            - "09 在本地建一个仓库": Git/GitBash/09_在本地建一个仓库.md
            - "10 三棵树": Git/GitBash/10_三棵树.md
            - "11 向本地仓库添加文件": Git/GitBash/11_向本地仓库添加文件.md
            - "12 status": Git/GitBash/12_status.md
            - "13 commit": Git/GitBash/13_commit.md
            - "14 log": Git/GitBash/14_log.md
            - "15 checkout file": Git/GitBash/15_checkout_file.md
            - "16 diff": Git/GitBash/16_diff.md
            - "17 reset": Git/GitBash/17_reset.md
            - "18 rm": Git/GitBash/18_rm.md
            - "19 branch & checkout branch": Git/GitBash/19_branch&checkout_branch.md
            - "20 制造冲突一": Git/GitBash/20_制造冲突一.md
            - "21 制造冲突二": Git/GitBash/21_制造冲突二.md
            - "22 制造冲突三": Git/GitBash/22_制造冲突三.md
            - "23 解决冲突": Git/GitBash/23_解决冲突.md
            - "24 merge": Git/GitBash/24_merge.md
            - "25 stash1": Git/GitBash/25_stash1.md
            - "26 stash2": Git/GitBash/26_stash2.md
            - "27 删除未合并的分支": Git/GitBash/27_删除未合并的分支.md
            - "28 推拉": Git/GitBash/28_推拉.md
            - "29 rebase": Git/GitBash/29_rebase.md
            - "30 tag": Git/GitBash/30_tag.md
            - "31 config": Git/GitBash/31_config.md

    - "Linux":
        - "<001-008> 基础知识":
            - "001 Unix": Linux/001_Unix.md
            - "002 Linux": Linux/002_Linux.md
            - "003 预备知识": Linux/003_预备知识.md
            - "004 分区": Linux/004_分区.md
            - "005 安装": Linux/005_安装.md
            - "006 常见目录及其作用": Linux/006_常见目录及其作用.md
            - "007 一些注意事项": Linux/007_一些注意事项.md
            - "008 命令格式": Linux/008_命令格式.md
        - "<009-016> 目标处理命令":
            - "009 ls": Linux/009_ls.md
            - "010 mkdir": Linux/010_mkdir.md
            - "011 cd": Linux/011_cd.md
            - "012 pwd": Linux/012_pwd.md
            - "013 rmdir": Linux/013_rmdir.md
            - "014 cp": Linux/014_cp.md
            - "015 mv": Linux/015_mv.md
            - "016 rm": Linux/016_rm.md
        - "<017-023> 文件处理命令":
            - "017 touch": Linux/017_touch.md
            - "018 cat": Linux/018_cat.md
            - "019 tac": Linux/019_tac.md
            - "020 more": Linux/020_more.md
            - "021 less": Linux/021_less.md
            - "022 head": Linux/022_head.md
            - "023 tail": Linux/023_tail.md
        - "024 链接命令 ln": Linux/024_ln.md
        - "<025-028> 权限管理命令":
            - "025 chmod": Linux/025_chmod.md
            - "026 chown": Linux/026_chown.md
            - "027 chgrp": Linux/027_chgrp.md
            - "028 umask": Linux/028_umask.md
        - "<029-033> 文件搜索命令":
            - "029 find": Linux/029_find.md
            - "030 locate": Linux/030_locate.md
            - "031 which": Linux/031_which.md
            - "032 whereis": Linux/032_whereis.md
            - "033 grep": Linux/033_grep.md
        - "<034-035> 帮助命令":
            - "034 man": Linux/034_man.md
            - "035 help": Linux/035_help.md
        - "<036-039> 用户管理命令":
            - "036 useradd": Linux/036_useradd.md
            - "037 passwd": Linux/037_passwd.md
            - "038 who": Linux/038_who.md
            - "039 w": Linux/039_w.md
        - "<040-046> 压缩解压命令":
            - "040 gzip": Linux/040_gzip.md
            - "041 gunzip": Linux/041_gunzip.md
            - "042 tar": Linux/042_tar.md
            - "043 zip": Linux/043_zip.md
            - "044 unzip": Linux/044_unzip.md
            - "045 bzip2": Linux/045_bzip2.md
            - "046 bunzip2": Linux/046_bunzip2.md
        - "<047-056> 网络命令":
            - "047 write": Linux/047_write.md
            - "048 well": Linux/048_wall.md
            - "049 ping": Linux/049_ping.md
            - "050 ifconfig": Linux/050_ifconfig.md
            - "051 mail": Linux/051_mail.md
            - "052 last": Linux/052_last.md
            - "053 lastlog": Linux/053_lastlog.md
            - "054 traceroute": Linux/054_traceroute.md
            - "055 netstat": Linux/055_netstat.md
            - "056 setup": Linux/056_setup.md
        - "057 挂载命令 mount": Linux/057_mount.md
        - "<058-060> 关机重启等命令":
            - "058 关机命令": Linux/058_关机命令.md
            - "059 重启命令": Linux/059_重启命令.md
            - "060 登出命令": Linux/060_logout.md
        - "<061-066> RPM 命令管理":
            - "061 软件包管理简介": Linux/061_软件包管理简介.md
            - "062 RPM 包的命名原则与依赖性": Linux/062_RPM_包名与依赖性.md
            - "063 RPM 包的安装、升级与卸载": Linux/063_RPM_包的安装、升级与卸载.md
            - "064 RPM 包的查询": Linux/064_RPM_包的查询.md
            - "065 RPM 包的校验": Linux/065_RPM_包的校验.md
            - "066 RPM 包的文件提取": Linux/066_RPM_包的文件提取.md
        - "<067-070> IP & yum":
            - "067 IP 地址的配置": Linux/067_IP_地址的配置.md
            - "068 网络 yum 源": Linux/068_网络_yum_源.md
            - "069 yum 命令": Linux/069_yum_命令.md
            - "070 光盘 yum 源搭建": Linux/070_光盘_yum_源搭建.md
        - "<071-072> 源码包安装":
            - "071 RPM 包与源码包的区别": Linux/071_RPM_包与源码包的区别.md
            - "072 源码包的安装过程": Linux/072_源码包的安装过程.md
        - "073 脚本安装": Linux/073_脚本安装包.md

    - "Python3":
        - "Basic Grammar":
            - "to be continued": Python3/Basic Grammar/to be continued.md
        - "Advance Grammar":
            - "to be continued": Python3/Advance Grammar/to be continued.md
        - "Exercises":
            - "PythonChallenge":
                - "00 warming up": Python3/Exercises/PythonChallenge/00_warming_up.md
                - "01 what about making trans": Python3/Exercises/PythonChallenge/01_what_about_making_trans.md
                - "02 ocr": Python3/Exercises/PythonChallenge/02_ocr.md
                - "03 re": Python3/Exercises/PythonChallenge/03_re.md
                - "04 follow the chain": Python3/Exercises/PythonChallenge/04_follow_the_chain.md
                - "05 peak hell": Python3/Exercises/PythonChallenge/05_peak_hell.md
                - "06 now there are pairs": Python3/Exercises/PythonChallenge/06_now_there_are_pairs.md
                - "07 smarty": Python3/Exercises/PythonChallenge/07_smarty.md
                - "08 working hard": Python3/Exercises/PythonChallenge/08_working_hard.md
                - "09 connect the dots": Python3/Exercises/PythonChallenge/09_connect_the_dots.md
                - "10 what are you looking at": Python3/Exercises/PythonChallenge/10_what_are_you_looking_at.md
                - "11 odd even": Python3/Exercises/PythonChallenge/11_odd_even.md
                - "12 dealing evil": Python3/Exercises/PythonChallenge/12_dealing_evil.md
                - "13 call him": Python3/Exercises/PythonChallenge/13_call_him.md
                - "14 walk around": Python3/Exercises/PythonChallenge/14_walk_around.md
                - "15 whom": Python3/Exercises/PythonChallenge/15_whom.md
                - "16 let me get this straight": Python3/Exercises/PythonChallenge/16_let_me_get_this_straight.md
                - "17 eat": Python3/Exercises/PythonChallenge/17_eat.md
                - "18 can you tell the difference": Python3/Exercises/PythonChallenge/18_can_you_tell_the_difference.md
                - "19 please": Python3/Exercises/PythonChallenge/19_please.md
                - "20 go away": Python3/Exercises/PythonChallenge/20_go_away.md
                - "21 dealing package.pack": Python3/Exercises/PythonChallenge/21_dealing_package-pack.md
                - "22 emulate": Python3/Exercises/PythonChallenge/22_emulate.md
                - "23 what is this mudule": Python3/Exercises/PythonChallenge/23_what_is_this_module.md
                - "24 from top to bottom": Python3/Exercises/PythonChallenge/24_from_top_to_bottom.md
                - "25 imagine how they sound": Python3/Exercises/PythonChallenge/25_imagine_how_they_sound.md
                - "26 be a man-apologize": Python3/Exercises/PythonChallenge/26_be_a_man-applogize.md
                - "27 between the tables": Python3/Exercises/PythonChallenge/27_between_the_tables.md
                - "28 many pairs ring-ring": Python3/Exercises/PythonChallenge/28_many_pairs_ring-ring.md
                - "29 silence": Python3/Exercises/PythonChallenge/29_silence.md
                - "30 relax you are on 30": Python3/Exercises/PythonChallenge/30_relax_you_are_on_30.md
                - "31 where am I": Python3/Exercises/PythonChallenge/31_where_am_I.md
                - "32 etch-a-scetch": Python3/Exercises/PythonChallenge/32_etch-a-scetch.md
                - "33 33 bottles of beer of wall": Python3/Exercises/PythonChallenge/33_33_bottles_of_beer_of_wall.md

    - "Tools":
        - "Jupyter Notebook":
            - "01 初识丘比特笔记本": Tools/JupyterNotebook/01_初识丘比特笔记本.md
            - "02 命令模式的快捷键": Tools/JupyterNotebook/02_命令模式的快捷键.md
            - "03 编辑模式的快捷键": Tools/JupyterNotebook/03_编辑模式的快捷键.md
        - "Markdown":
            - "01 目录与标题": Tools/Markdown/01_目录与标题.md
            - "02 块注释与标记": Tools/Markdown/02_块注释与标记.md
            - "03 代码块": Tools/Markdown/03_代码块.md
            - "04 表格": Tools/Markdown/04_表格.md
            - "05 转义字符": Tools/Markdown/05_转义字符.md
            - "06 列表": Tools/Markdown/06_列表.md
            - "07 分割线": Tools/Markdown/07_分割线.md
            - "08 下划线": Tools/Markdown/08_下划线.md
            - "09 删除线": Tools/Markdown/09_删除线.md
            - "10 “三体”": Tools/Markdown/10_“三体”.md
            - "11 上下标与注脚": Tools/Markdown/11_上下标与注脚.md
            - "12 插入链接": Tools/Markdown/12_插入链接.md
            - "13 插入图片": Tools/Markdown/13_插入图片.md
            - "14 YAML 题头": Tools/Markdown/14_YAML题头.md
            - "15 缩写": Tools/Markdown/15_缩写.md
            - "16 kbd & to do list": Tools/Markdown/16_两个有意思的功能.md
            - "17 emoji": Tools/Markdown/17_emoji.md
            - "18 LaTex": Tools/Markdown/18_LaTeX.md
            - "19 flow": Tools/Markdown/19_flow.md
            - "20 GANTT": Tools/Markdown/20_GANTT.md
            - "21 UML": Tools/Markdown/21_UML.md
        - "MkDocs":
            - "00 快速上手": Tools/MkDocs/00_快速上手.md
            - "01 安装": Tools/MkDocs/01_安装.md
            - "02 新建日志项目": Tools/MkDocs/02_新建日志项目.md
            - "03 编辑 mkdocs.yml": Tools/MkDocs/03_编辑配置文件.md
            - "04 公式的使用": Tools/MkDocs/04_公式的使用.md
            - "05 导出": Tools/MkDocs/05_导出.md
            - "06 将网站放到互联网上": Tools/MkDocs/06_将网站放到互联网上.md
            - "07 MkDocs 上的 Markdown": Tools/MkDocs/07_MkDocs-Markdown.md
        - "Vim":
            - "01 “3+1”种膜模式": Tools/Vim/01_三加一种模式.md
            - "02 定位命令": Tools/Vim/02_定位命令.md
            - "03 删除命令": Tools/Vim/03_删除命令.md
            - "04 插入命令": Tools/Vim/04_插入命令.md
            - "05 删除并插入": Tools/Vim/05_删除并插入.md
            - "06 复制与粘贴": Tools/Vim/06_复制与粘贴.md
            - "07 搜索与替换": Tools/Vim/07_搜索与替换.md
            - "08 后悔药与特殊字符": Tools/Vim/08_后悔药与特殊字符.md
            - "09 保存与退出": Tools/Vim/09_保存与退出.md
            - "10 偷懒用的命令": Tools/Vim/10_偷懒用的命令.md
            - "11 简洁流配置": Tools/Vim/11_简洁流配置.md
        - "搭建个人博客":
            - "01 搭建博客的几种选择": Tools/搭建个人博客/01_搭建博客的几种选择.md
            - "02 几种博客工具简介": Tools/搭建个人博客/02_几种博客工具简介.md
            - "03 docsify": Tools/搭建个人博客/03_docsify.md
            - "04 gridea": Tools/搭建个人博客/04_gridea.md
            - "05 hexo": Tools/搭建个人博客/05_hexo.md

    - "Web":
        - "HTML5":
            - "to be continued": Web/HTML5/to be continued.md
        - "CSS3":
            - "to be continued": Web/CSS3/to be continued.md
        - "Javascript":
            - "to be continued": Web/Javascript/to be continued.md

    - "about": about.md
