# Project information
site_name: YorkFish's blog
site_url: https://yorkfish.github.io/blogs/
site_author: YorkYu
site_description: notes of learning

# Copyright
copyright: 'Copyright &copy; 2020 - 2021 YorkFish'

# Configuration
theme:
  name: material
  language: zh
  features:
    - tabs

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yorkfish
      name: github

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - index: index.md
  - about: about.md
  - Editors:
    - "Preview": editors/preview.md
    - "Jupyter Notebook":
      - "01 安装并修改默认开启路径": editors/jupyter-notebook/01-install.md
      - "02 初识": editors/jupyter-notebook/02-first-acquaintance.md
      - "03 命令模式的快捷键": editors/jupyter-notebook/03-shortcut-keys-for-command-mode.md
      - "04 编辑模式的快捷键": editors/jupyter-notebook/04-shortcut-key-for-edit-mode.md
    - "Sublime Text 3":
      - "01 基础设置": editors/sublime-text-3/01-basic-settings.md
      - "02 快捷键": editors/sublime-text-3/02-shortcut-keys.md
      - "03 Python3 运行环境": editors/sublime-text-3/03-python3-operating-env.md
      - "04 C 运行环境": editors/sublime-text-3/04-c-operating-env.md
      - "05 C++ 运行环境": editors/sublime-text-3/05-cpp-operating-env.md
      - "06 Makefile": editors/sublime-text-3/06-makefile.md
      - "07 HTML 运行环境": editors/sublime-text-3/07-html-operating-env.md
      - "08 Snippet": editors/sublime-text-3/08-snippet.md
      - "09 Plugin": editors/sublime-text-3/09-plugin.md
      - "Plugins":
        - "01 Package Control": editors/sublime-text-3/plugins/01-package-control.md
        - "02 A File Icon": editors/sublime-text-3/plugins/02-a-file-icon.md
        - "03 Anaconda": editors/sublime-text-3/plugins/03-anaconda.md
        - "04 ConvertToUTF8": editors/sublime-text-3/plugins/04-convert-to-utf-8.md
        - "05 Python PEP8 Autoformat": editors/sublime-text-3/plugins/05-python-pep8-autoformat.md
        - "06 SublimeGDB": editors/sublime-text-3/plugins/06-sublimegdb.md
        - "07 sublimeREPL": editors/sublime-text-3/plugins/07-sublimerepl.md
        - "08 Theme - ayu": editors/sublime-text-3/plugins/08-theme-ayu.md
        - "09 Theme - Spacegray": editors/sublime-text-3/plugins/09-theme-spacegray.md
        - "10 Vintageous": editors/sublime-text-3/plugins/10-vintageous.md
        - "11 Virtualenv": editors/sublime-text-3/plugins/11-virtualenv.md
    - "Vim":
      - "Gvim":
        - "01 几种模式": editors/vim/gvim/01-several-modes.md
        - "02 定位命令": editors/vim/gvim/02-positioning-command.md
        - "03 删除命令": editors/vim/gvim/03-delete-command.md
        - "04 插入命令": editors/vim/gvim/04-insert-command.md
        - "05 删除并插入": editors/vim/gvim/05-delete-and-insert.md
        - "06 复制与粘贴": editors/vim/gvim/06-copy-and-paste.md
        - "07 搜索与替换": editors/vim/gvim/07-search-and-replace.md
        - "08 后悔药与特殊字符": editors/vim/gvim/08-regret-medicine-and-special-characters.md
        - "09 保存与退出": editors/vim/gvim/09-save-and-exit.md
        - "10 多行注释": editors/vim/gvim/10-multiline-comments.md
        - "11 宏与补全": editors/vim/gvim/11-macro-and-complete.md
        - "12 映射": editors/vim/gvim/12-map.md
        - "13 合并文件与打开多个文件": editors/vim/gvim/13-files.md
        - "14 简洁流配置": editors/vim/gvim/14-simple-configuration.md
        - "15 有意思的命令": editors/vim/gvim/15-interesting-order.md
      - "Neovim":
        - "01 安装": editors/vim/neovim/01-install.md
        - "02 基本设置": editors/vim/neovim/02-basic-settings.md
        - "03 基本映射": editors/vim/neovim/03-basic-mappings.md
        - "04 光标移动": editors/vim/neovim/04-cursor-movement.md
        - "05 分屏": editors/vim/neovim/05-window-management.md
        - "06 标签页": editors/vim/neovim/06-tab-management.md
        - "07 配色设置": editors/vim/neovim/07-color.md
        - "08 Markdown": editors/vim/neovim/08-markdown-settings.md
        - "09 一键执行": editors/vim/neovim/09-one-click-execution.md
        - "10 checkhealth": editors/vim/neovim/10-checkhealth.md
        - "Plugins":
          - "01 Vim-Plug 的使用": editors/vim/neovim/plugins/01-vim-plug.md
          - "02 coc.nvim": editors/vim/neovim/plugins/02-coc-nvim.md
          - "03 NERDTree": editors/vim/neovim/plugins/03-nerdtree.md
          - "04 vim-airline": editors/vim/neovim/plugins/04-vim-airline.md
    - "VS Code":
      - "01 Python 环境": editors/vscode/01-for-python.md
      - "02 C 环境": editors/vscode/02-for-c.md
      - "03 C++ 环境": editors/vscode/03-for-cpp.md
      - "04 vim": editors/vscode/04-vim.md
      - "05 彩虹屁": editors/vscode/05-rainbow-fart.md
      - "06 Snippet": editors/vscode/06-markdown-snippet.md
      - "07 终端样式": editors/vscode/07-terminal.md
      - "08 gitbash - env": editors/vscode/08-gitbash-virtualenv.md
  - Git:
    - "Preview": git/preview.md
    - "GitHub 上的使用":
      - "01 在 GitHub 上新建仓库": git/github/01-new-repository-on-github.md
      - "02 往仓库里添加文件": git/github/02-add-file-to-the-repository.md
      - "03 修改仓库里的文件": git/github/03-modify-file-in-the-repository.md
      - "04 查看历史记录": git/github/04-view-history.md
      - "05 创建分支": git/github/05-create-a-branch.md
      - "06 切换分支": git/github/06-switch-branch.md
      - "07 查看历史图像": git/github/07-view-historical-images.md
      - "08 合并分支": git/github/08-merge-branches.md
      - "09 将远程仓库克隆到本地": git/github/09-clone-the-remote-repo-locally.md
    - "GitBash 下的操作":
      - "01 设置身份信息": git/gitbash/01-set-identity-information.md
      - "02 创建 SSH Key": git/gitbash/02-create-ssh-key.md
      - "03 在 GitHub 上添加公钥": git/gitbash/03-add-the-public-key.md
      - "04 克隆远程仓库": git/gitbash/04-clone.md
      - "05 本地仓库关联远程仓库": git/gitbash/05-remote-add.md
      - "06 本地仓库向远程仓库推送": git/gitbash/06-push.md
      - "07 解决连接失败的问题": git/gitbash/07-fix-failed-connection.md
      - "08 删除远程仓库": git/gitbash/08-remove-remote-repository.md
      - "09 在本地建一个仓库": git/gitbash/09-create-a-new-repo-locally.md
      - "10 三棵树": git/gitbash/10-three-trees.md
      - "11 添加": git/gitbash/11-add-file-to-local-repo.md
      - "12 查看状态": git/gitbash/12-status.md
      - "13 提交": git/gitbash/13-commit.md
      - "14 查看记录": git/gitbash/14-log.md
      - "15 回滚文件": git/gitbash/15-checkout-file.md
      - "16 查看更改": git/gitbash/16-diff.md
      - "17 逆转未来": git/gitbash/17-reset.md
      - "18 删除": git/gitbash/18-rm.md
      - "19 分支": git/gitbash/19-branch.md
      - "20 制造冲突一": git/gitbash/20-create-conflict-1.md
      - "21 制造冲突二": git/gitbash/21-create-conflict-2.md
      - "22 制造冲突三": git/gitbash/22-create-conflict-3.md
      - "23 解决冲突": git/gitbash/23-conflict-resolution.md
      - "24 合并分支": git/gitbash/24-merge.md
      - "25 stash1": git/gitbash/25-stash1.md
      - "26 stash2": git/gitbash/26-stash2.md
      - "27 删除未合并的分支": git/gitbash/27-delete-merged-branches.md
      - "28 推拉": git/gitbash/28-push-and-pull.md
      - "29 rebase": git/gitbash/29-rebase.md
      - "30 标签": git/gitbash/30-tag.md
      - "31 config": git/gitbash/31-config.md
  - Linux:
    - "基础知识":
      - "001 Unix": Linux/001_Unix.md
      - "002 Linux": Linux/002_Linux.md
      - "003 预备知识": Linux/003_预备知识.md
      - "004 分区": Linux/004_分区.md
      - "005 安装": Linux/005_安装.md
      - "006 常见目录及其作用": Linux/006_常见目录及其作用.md
      - "007 一些注意事项": Linux/007_一些注意事项.md
      - "008 命令格式": Linux/008_命令格式.md
    - "目标处理命令":
      - "009 ls": Linux/009_ls.md
      - "010 mkdir": Linux/010_mkdir.md
      - "011 cd": Linux/011_cd.md
      - "012 pwd": Linux/012_pwd.md
      - "013 rmdir": Linux/013_rmdir.md
      - "014 cp": Linux/014_cp.md
      - "015 mv": Linux/015_mv.md
      - "016 rm": Linux/016_rm.md
    - "文件处理命令":
      - "017 touch": Linux/017_touch.md
      - "018 cat": Linux/018_cat.md
      - "019 tac": Linux/019_tac.md
      - "020 more": Linux/020_more.md
      - "021 less": Linux/021_less.md
      - "022 head": Linux/022_head.md
      - "023 tail": Linux/023_tail.md
    - "链接命令":
      - "024 链接命令 ln": Linux/024_ln.md
    - "权限管理命令":
      - "025 chmod": Linux/025_chmod.md
      - "026 chown": Linux/026_chown.md
      - "027 chgrp": Linux/027_chgrp.md
      - "028 umask": Linux/028_umask.md
    - "文件搜索命令":
      - "029 find": Linux/029_find.md
      - "030 locate": Linux/030_locate.md
      - "031 which": Linux/031_which.md
      - "032 whereis": Linux/032_whereis.md
      - "033 grep": Linux/033_grep.md
    - "帮助命令":
      - "034 man": Linux/034_man.md
      - "035 help": Linux/035_help.md
    - "用户管理命令":
      - "036 useradd": Linux/036_useradd.md
      - "037 passwd": Linux/037_passwd.md
      - "038 who": Linux/038_who.md
      - "039 w": Linux/039_w.md
    - "压缩解压命令":
      - "040 gzip": Linux/040_gzip.md
      - "041 gunzip": Linux/041_gunzip.md
      - "042 tar": Linux/042_tar.md
      - "043 zip": Linux/043_zip.md
      - "044 unzip": Linux/044_unzip.md
      - "045 bzip2": Linux/045_bzip2.md
      - "046 bunzip2": Linux/046_bunzip2.md
    - "网络命令":
      - "047 write": Linux/047_write.md
      - "048 well": Linux/048_wall.md
      - "049 ping": Linux/049_ping.md
      - "050 ifconfig": Linux/050_ifconfig.md
      - "051 mail": Linux/051_mail.md
      - "052 last": Linux/052_last.md
      - "053 lastlog": Linux/053_lastlog.md
      - "054 traceroute": Linux/054_traceroute.md
      - "055 netstat": Linux/055_netstat.md
      - "056 setup": Linux/056_setup.md
    - "挂载命令":
      - "057 挂载命令 mount": Linux/057_mount.md
    - "关机重启等命令":
      - "058 关机命令": Linux/058_关机命令.md
      - "059 重启命令": Linux/059_重启命令.md
      - "060 登出命令": Linux/060_logout.md
    - "RPM 命令管理":
      - "061 软件包管理简介": Linux/061_软件包管理简介.md
      - "062 RPM 包的命名原则与依赖性": Linux/062_RPM_包名与依赖性.md
      - "063 RPM 包的安装、升级与卸载": Linux/063_RPM_包的安装、升级与卸载.md
      - "064 RPM 包的查询": Linux/064_RPM_包的查询.md
      - "065 RPM 包的校验": Linux/065_RPM_包的校验.md
      - "066 RPM 包的文件提取": Linux/066_RPM_包的文件提取.md
    - "IP & yum":
      - "067 IP 地址的配置": Linux/067_IP_地址的配置.md
      - "068 网络 yum 源": Linux/068_网络_yum_源.md
      - "069 yum 命令": Linux/069_yum_命令.md
      - "070 光盘 yum 源搭建": Linux/070_光盘_yum_源搭建.md
    - "源码包安装":
      - "071 RPM 包与源码包的区别": Linux/071_RPM_包与源码包的区别.md
      - "072 源码包的安装过程": Linux/072_源码包的安装过程.md
    - "脚本安装":
      - "073 脚本安装": Linux/073_脚本安装包.md
